<a href="https://colab.research.google.com/github/ravi18kumar2021/30Days-DS-to-GenAI/blob/main/Day02/Interview_QA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ❓ Interview Questions

**1. What is broadcasting in NumPy?**

**Ans:** Broadcasting is a special feature of NumPy arrays. In element-wise operations, the smaller array is automatically expanded to match the shape of the larger array.

In [3]:
import numpy as np

In [8]:
arr1 = np.array([[3, 4, 1], [5, 3, 7]])
arr1

array([[3, 4, 1],
       [5, 3, 7]])

In [9]:
arr2 = np.array([5, 3, 8])
arr2

array([5, 3, 8])

In [10]:
arr1 + arr2

array([[ 8,  7,  9],
       [10,  6, 15]])

**2. How do you calculate the dot product using NumPy?**

In [11]:
np.dot(arr1, arr2)

array([35, 90])

In [12]:
arr1 @ arr2

array([35, 90])

**3. How does NumPy achieve faster performance than regular Python?**

**Ans:** Since, NumPy is written in C language, its implementation allows fast access to contiguous memory which enables it to perform vectorized operations more effiently.

**4. What is the shape vs. size of a NumPy array?**

**Ans:** The shape property of NumPy array gives information of number of items along each axis in a particular dimension.

Whereas, the size property denotes the number of total elements in the array.

In [24]:
arr1 = np.array([[3, 5], [1, 4], [3, 7]])
arr1.shape

(3, 2)

In [26]:
arr2 = np.array([[[2, 5], [4, 3]]])
arr2.shape

(1, 2, 2)

In [27]:
arr1.size

6

In [28]:
arr2.size

4

**5. What’s the difference between a[0] and a[[0]]?**

**Ans:** a[0] returns a view that is one dimension lower than the original array.

Whereas a[[0]] return a sub-array with the same number of dimension of the original array.

In [44]:
a = np.array([2, 3, 6]) # 1D array
a

array([2, 3, 6])

In [45]:
a[0] # one dimension lower than 1D

np.int64(2)

In [46]:
a[[0]] # 1D array

array([2])

In [47]:
b = np.array([[3, 5, 6], [2, 4, 5]]) # 2D array
b

array([[3, 5, 6],
       [2, 4, 5]])

In [48]:
b[0] # one dimension lower than 2D

array([3, 5, 6])

In [49]:
b[[0]] # 2D array

array([[3, 5, 6]])

In [50]:
c = np.array([[[2, 5, 6], [1, 5, 7]]]) # 3D array
c

array([[[2, 5, 6],
        [1, 5, 7]]])

In [51]:
c[0] # one dimension lower than 3D

array([[2, 5, 6],
       [1, 5, 7]])

In [52]:
c[[0]] # 3D array

array([[[2, 5, 6],
        [1, 5, 7]]])