<a href="https://colab.research.google.com/github/ravi18kumar2021/30Days-DS-to-GenAI/blob/main/Day02/Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Creating Array

In [2]:
a = np.array(4)
b = np.array([3, 7, 8])
c = np.array([[2, 4], [5, 8]])

In [3]:
a

array(4)

In [4]:
b

array([3, 7, 8])

In [5]:
c

array([[2, 4],
       [5, 8]])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [16]:
np.linspace(5, 10, 3)

array([ 5. ,  7.5, 10. ])

### Array Properties

In [17]:
c

array([[2, 4],
       [5, 8]])

In [18]:
c.dtype # data type

dtype('int64')

In [19]:
c.ndim # number of dimension

2

In [20]:
c.shape # number of rows, cols

(2, 2)

In [21]:
c.size # total elements

4

### Indexing and Slicing

In [22]:
a = np.array([[2, 5, 8], [1, 2, 3]])
a

array([[2, 5, 8],
       [1, 2, 3]])

In [23]:
a[0]

array([2, 5, 8])

In [24]:
a[0][1]

np.int64(5)

In [25]:
a[0, 1]

np.int64(5)

In [26]:
a[-1, -1]

np.int64(3)

In [27]:
a[:, 1]

array([5, 2])

In [28]:
a[0:2, 2]

array([8, 3])

In [29]:
a[0, 1:]

array([5, 8])

### Broadcasting

In [30]:
a

array([[2, 5, 8],
       [1, 2, 3]])

In [31]:
b

array([3, 7, 8])

In [32]:
a + b

array([[ 5, 12, 16],
       [ 4,  9, 11]])

In [33]:
a * b

array([[ 6, 35, 64],
       [ 3, 14, 24]])

### Vectorized Operations: (replaces loop with element wise operations)

In [37]:
c

array([[2, 4],
       [5, 8]])

In [39]:
d = c**2
d

array([[ 4, 16],
       [25, 64]])

In [40]:
c + d

array([[ 6, 20],
       [30, 72]])

### Boolean Masking and Filtering

In [41]:
a

array([[2, 5, 8],
       [1, 2, 3]])

In [43]:
a > 4

array([[False,  True,  True],
       [False, False, False]])

In [44]:
a[a > 4]

array([5, 8])

### Reshape and Flatten

In [45]:
a

array([[2, 5, 8],
       [1, 2, 3]])

In [46]:
a.shape

(2, 3)

In [47]:
a.reshape(3, 2) # convert shape into 3 rows and 2 columns

array([[2, 5],
       [8, 1],
       [2, 3]])

In [48]:
a.flatten() # convert 2D into 1D

array([2, 5, 8, 1, 2, 3])

### Aggregate Functions

In [49]:
a

array([[2, 5, 8],
       [1, 2, 3]])

In [50]:
a.sum()

np.int64(21)

In [53]:
a.sum(axis=0) # column wise

array([ 3,  7, 11])

In [54]:
a.sum(axis=1) # row wise

array([15,  6])

In [55]:
a.mean(axis=1)

array([5., 2.])

### Linear Algebra

In [59]:
c

array([[2, 4],
       [5, 8]])

In [58]:
d

array([[ 4, 16],
       [25, 64]])

In [60]:
np.dot(c, d)

array([[108, 288],
       [220, 592]])

In [61]:
c @ d

array([[108, 288],
       [220, 592]])

In [62]:
c.T

array([[2, 5],
       [4, 8]])

In [63]:
d.T

array([[ 4, 25],
       [16, 64]])

### Random Numbers

In [64]:
np.random.rand() # 0 to 1

0.014111188029990562

In [66]:
np.random.rand(3)

array([0.94473184, 0.50207632, 0.01431123])

In [67]:
np.random.rand(3, 2)

array([[0.20541373, 0.19139899],
       [0.97936228, 0.98154288],
       [0.9263271 , 0.05721547]])

In [70]:
np.random.randint(2, 5) # random integer values

4

In [72]:
np.random.randint(3, 6, (2, 3))

array([[3, 5, 5],
       [4, 4, 3]])

In [74]:
np.random.randn(3) # normal distributed values

array([ 0.09509396,  0.11800305, -1.29617017])

In [75]:
np.random.randn(1, 3)

array([[1.05740399, 0.53772429, 0.27004907]])

In [76]:
np.random.rand(3, 2)

array([[0.19621615, 0.44436209],
       [0.96748382, 0.87840945],
       [0.37399749, 0.25506889]])

In [86]:
np.random.seed(5) # same random output
np.random.rand(4, 5)

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781]])

### Mini Tasks

Q. Create a 2D NumPy array with the following structure:

[[1, 2, 3],

[4, 5, 6]]

then print shape, size and data type

In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr.shape

(2, 3)

In [89]:
arr.size

6

In [90]:
arr.dtype

dtype('int64')

Q. Start with this 1D array: [1, 2, 3, 4, 5, 6]

- Reshape it into a 2x3 matrix.
- Flatten back it into a 1D array.

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [92]:
arr = arr.reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

Q. Given an array [1, 2, 3], sqaure each element and add 10 to each element.

In [94]:
arr = np.array([1, 2, 3])
arr**2

array([1, 4, 9])

In [95]:
arr + 10

array([11, 12, 13])

Q. Given an array [5, 10, 15, 20, 25], filter only the values greater than 12.

In [96]:
arr = np.array([5, 10, 15, 20, 25])
arr[arr > 12]

array([15, 20, 25])

Q. create two 2x2 matrices:

[[1, 2],

[3, 4]]

and

[[5, 6],

[7, 8]]

Compute the matrix product

In [97]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [98]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [99]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [100]:
a @ b

array([[19, 22],
       [43, 50]])