<a href="https://colab.research.google.com/github/ravi18kumar2021/30Days-DS-to-GenAI/blob/main/Day02/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Program Execution:

- Ask matrix 1 and matrix 2 elements
- ask matrix dimensions
- display outputs of various operations

In [4]:
def user_inputs():
  '''
  Prompt the user to input two arrays and their shapes
  Returns array1, array2, shape1, shape2
  '''
  matrix1_inputs = input('Enter elements of matrix 1 separated by spaces : ')
  matrix2_inputs = input('Enter elements of matrix 2 separated by spaces : ')
  array1 = np.array(list(map(int, matrix1_inputs.split())))
  array2 = np.array(list(map(int, matrix2_inputs.split())))
  matrix1_shape = input('Enter shape of matrix 1 separated by a space : ')
  matrix2_shape = input('Enter shape of matrix 2 separated by a space : ')
  shape1 = tuple(map(int, matrix1_shape.split()))
  shape2 = tuple(map(int, matrix2_shape.split()))
  return array1, array2, shape1, shape2

In [5]:

def perform_operations(matrix1, matrix2):
  '''
  Returns the outputs of various operations performed on two matrices
  '''
  try:
    addition = multiplication = dot_product = None
    if matrix1.shape == matrix2.shape:
      addition = np.add(matrix1, matrix2)
      multiplication = np.multiply(matrix1, matrix2)
    if (matrix1.shape[1] == matrix2.shape[0]):
      dot_product = np.dot(matrix1, matrix2)
    transpose1 = matrix1.T
    transpose2 = matrix2.T
    return addition, multiplication, dot_product, transpose1, transpose2
  except Exception as error:
    print('Error during operation :', error)

In [6]:
def display(title, operation):
  '''
  Prints title and the result of the corresponding matrix operation
  '''
  print()
  print(title)
  print(operation if operation is not None else "Not Applicable")
  print()

In [7]:
def matrix_calculator():
  '''
  Returns Various Matrix Operations performed on Matrix 1 and Matrix 2
  '''
  try:
    array1, array2, shape1, shape2 = user_inputs()
    matrix1 = array1.reshape(shape1)
    matrix2 = array2.reshape(shape2)
    addition, multiplication, dot_product, transpose1, transpose2 = perform_operations(matrix1, matrix2)
    display('Addition:-', addition)
    display('Multiplication:-', multiplication)
    display('Dot Product:-', dot_product)
    display('Transpose of Matrix 1:-', transpose1)
    display('Transpose of Matrix 2:-', transpose2)
  except Exception as error:
    print('Error :', error)

In [8]:
matrix_calculator()

Enter elements of matrix 1 separated by spaces : 3 5 8 3 1 3
Enter elements of matrix 2 separated by spaces : 2 3 5 7 2 2
Enter shape of matrix 1 separated by a space : 2 3
Enter shape of matrix 2 separated by a space : 2 3

Addition:-
[[ 5  8 13]
 [10  3  5]]


Multiplication:-
[[ 6 15 40]
 [21  2  6]]


Dot Product:-
Not Applicable


Transpose of Matrix 1:-
[[3 3]
 [5 1]
 [8 3]]


Transpose of Matrix 2:-
[[2 7]
 [3 2]
 [5 2]]

